// This file is automatically generated by build.rs

pub const APP_VERSION: &'static str = "0.1.0";
pub const APP_API_VERSION: &'static str = "1.0.0";
pub const APP_GAS_DEPLOYMENT_ID: &'static str = "AKfycbw2-g7PbX1lr7C-keieCtPo7t6iRtV3V8WdkUximh6UFXn6mlJxceNVItGV7VhS8GMqTg";
pub const APP_GITHUB_URL: &'static str = "https://github.com/st-little/anshin-meshi";
pub const APP_GA_TRACKING_ID: &'static str = "G-QK8F1Y6VFN";
